# -*- coding: utf-8 -*-
"""A12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154q_W9b4ladBEbO2J4fIqy7QAUv6yNx1
"""

print("Hello world")

print("hey")

print("hey")

print("hey", end="-")
print("tushar")
print("goyal")

a = 20
print(a)

a = "twenty"
print(a)

x =20
print( type(x))

x = "20"
print(type(x))

gender = "20"
gender = '20'
print(type(gender))
print(type(gender))

address = """jaipur
 rajasthan
 mansarovar """
 print(address)

address = """jaipur
 rajasthan
 mansarovar """
 print(address)

address = """jaipur rajasthan mansarovar """
print(address)

#string format

year= 2025
company ="regex"
print("current year is", company )

#string...
year= 2025
company ="regex"
print(f"current {year} is, company is =>{company}" )

username="tushar"
msg=f"my name is {username}"
print(msg)

username="abhishek"
print(msg)

#srting format using dot method
"current year is {} company is => {}". format(2025, "regex")

"current year is {} company is => {}". format(year, company)

#learning assignment

python version 2 and 3

3+2/2*4-1

x =20
x-=4
print(x)

10>2 and 10>3

10>20 or 10>50

not 50>20 and 10>20

10>2 or 10>5 and 10>70

#membership operator

"R" in "regex"

"R" not in "regex"

#what is bitwise operator

#what is identity operator
# ASCII value and UTF DIFFERNCE

#string indexing and Slicing

state = "Rajasthan"
print(state[4])

#Slicing
#[start : stop : [step=1]]

state= "Rajasthan"
print(state[0:4 ])

state= "Rajasthan"
print(state[4: ])

state= "Rajasthan"
print(state[ :4 ])

state= "Rajasthan"
print(state[ :9 ])

state= "Rajasthan"
print(state[ 2:8:2 ])#step size

state= "Rajasthan"
print(state[0:4:-1 ])

state= "Rajasthan"
print(state[-1:-4:-1 ])

state= "Rajasthan"
print(state[ : : -1 ])

state= "RAJASTHAN"
print(state[3:: -1 ])

num = 1000
if num == 10:
    print("Number is 10")
else:
    print("condition is false")

num = 8

if num % 2 == 0:
    print("Number is divisible by 2")
else:
    print("Number is not divisible by 2")

    if num % 3 == 0:
        print("Number is divisible by 3")
    else:
        print("Condition is false")

#uses of elif

num = 9

if num % 2 == 0:
    print("Number is divisible by 2")
elif num % 3 == 0:
    print("Number is divisible by 3")
else:
    print("Condition is false")

# take number 2 and 3 is divided by 6
# take a variable name as age if the age is grater than 10 print young agar 25 se jada h toh adult agar 35 married 60 senior citizen ohterwise child

age = int(input("Enter your age: "))

if age > 60:
    print("Senior Citizen")
elif age > 35 and age < 60:
    print("Married")
elif age > 25 and age < 35:
    print("Adult")
elif age > 10 and age < 25:
    print("Young")
else:
    print("Child")

age = int(input("Enter your age: "))

if age > 60:
    print("Senior Citizen")
elif age > 35 and age < 60:
    print("Married")
elif age > 25 and age < 35:
    print("Adult")
elif age > 10 and age < 25:
    print("Young")
else:
    print("Child")

# nested if else

# agar number 3 se divide hua print number is divided by 3 and number 3 and 5
#  donos
#  eehua divided by 15 other wise number is neither divided bu 3 nor 5 using
#  nested
  if esle



number = int(input("Enter a number: "))

if number % 3 == 0:
    if number % 5 == 0:
        print("Number is divided by 15")
    else:
        print("Number is divided by 3")
else:
    if number % 5 == 0:
        print("Number is divided by 5")
    else:
        print("Number is neither divided by 3 nor 5")

# variabe year k naam se and muje check krna woh yearb is leap year or not divid
# e by 4 until unless number is divide by


year = int(input("Enter a year: "))

if year % 4 == 0:
    if year % 100 == 0:
        if year % 400 == 0:
            print(f"{year} is a Leap Year")
        else:
            print(f"{year} is not a Leap Year")
    else:
        print(f"{year} is a Leap Year")
else:
    print(f"{year} is not a Leap Year")

# Assignment-1 (25/04/2025)
# Q1 Write a program that takes an integer input from the user and checks whether the number is odd or even.

num = int(input("Enter an integer: "))

# Checking if the number is even or odd
if num % 2 == 0:
    print(f"{num} is even.")
else:
    print(f"{num} is odd.")

# Q2 Write a program that takes three numbers as input and prints the largest of the three.

# Q3 Write a program to check if a given year is a leap year. A leap year is divisible by 4 but not by 100 unless it is also divisible by 400.

year = int(input("Enter a year: "))

if year % 400 == 0:
    print(f"{year} is a leap year.")
elif year % 100 == 0:
    print(f"{year} is not a leap year.")
elif year % 4 == 0:
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

# Q4 Write a program that takes a percentage (integer) as input and prints the corresponding grade based
# on the following criteria:
# >= 90: Grade A
# >= 80: Grade B
# >= 70: Grade C
# >= 60: Grade D
# < 60: Grade F





percentage = int(input("Enter your percentage: "))


if percentage >= 90:
    grade = 'A'
elif percentage >= 80:
    grade = 'B'
elif percentage >= 70:
    grade = 'C'
elif percentage >= 60:
    grade = 'D'
else:
    grade = 'F'

print(f"Your grade is: {grade}")

# Q5 Write a program that checks if a given letter is a vowel (a, e, i, o, u) or a consonant.


letter = input("Enter a single alphabet letter: ").lower()

if len(letter) == 1 and 'a' <= letter <= 'z':
    if letter in ['a', 'e', 'i', 'o', 'u']:
        print(f"{letter} is a vowel.")
    else:
        print(f"{letter} is a consonant.")
else:
    print("Invalid input. Please enter a single alphabet letter.")

# Q6 Write a basic calculator program that takes two numbers and an operator (+, -, *, /) as input and performs the specified operation. Print the result based on the operation.

# Q7 Write a program that takes a number as input and checks whether it is positive, negative, or zero.

num = float(input("Enter a number: "))


if num > 0:
    print(f"{num} is a positive number.")
elif num < 0:
    print(f"{num} is a negative number.")
else:
    print("The number is zero.")

# # Write a program that checks if a username and password entered by the user match the pre-set values
# username = "admin" and password = "1234". If both match, print "Login Successful", otherwise print
# "Login Failed".


username = "admin"
password = "1234"


entered_username = input("Enter username: ")
entered_password = input("Enter password: ")


if entered_username == username and entered_password == password:

    print("Login Successful")
else:
    print("Login Failed")

# Q9 Write a program that takes three sides of a triangle as input and checks if those sides form a valid
# triangle. A triangle is valid if the sum of any two sides is greater than the third side.
# Check conditions like a + b > c, b + c > a, and a + c > b.


a = float(input("Enter first side: "))
b = float(input("Enter second side: "))
c = float(input("Enter third side: "))


if (a + b > c) and (b + c > a) and (a + c > b):
    print("It is a valid triangle.")
else:
    print("It is not a valid triangle.")

# Q10 Write a program that calculates the Body Mass Index (BMI) based on user input for weight (in
# kilograms) and height (in meters). Then categorize the BMI into:
# Underweight (BMI < 18.5)
# Normal weight (18.5 <= BMI < 24.9)
# Overweight (25 <= BMI < 29.9)
# Obesity (BMI >= 30)
# Use the formula: BMI = weight / (height ** 2)


# Taking user input
weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))


bmi = weight / (height ** 2)

# Displaying BMI
print(f"Your BMI is: {bmi:.2f}")

if bmi < 18.5:
    print("Category: Underweight")
elif 18.5 <= bmi < 24.9:

    print("Category: Normal weight")
elif 25 <= bmi < 29.9:
    print("Category: Overweight")
else:
    print("Category: Obesity")

# Q11 Write a program that calculates the discount for a product based on its price:
# If price is greater than 1000, discount is 10%
# If price is between 500 and 1000, discount is 5%
# Otherwise, no discount
# Print the final price after applying the discount.


# Taking input of product price
price = float(input("Enter the price of the product: "))

# Calculating discount
if price > 1000:
    discount = price * 0.10
elif 500 <= price <= 1000:
    discount = price * 0.05
else:
    discount = 0

# Calculating final price
final_price = price - discount

# Displaying the final price
print(f"Discount applied: ₹{discount:.2f}")
print(f"Final price after discount: ₹{final_price:.2f}")

# Q12 Write a program that takes the name of a month as input and prints the number of days in that
# month. Consider leap years for February.

# Q13 Write a program that simulates a simple ATM. The user should be able to:
# Check balance
# Deposit money
# Withdraw money (ensure the balance doesn't go negative) Use an if-else structure to handle the user's

# choices.

# Initial balance
balance = 5000

# Displaying menu
print("Welcome to the ATM!")
print("1. Check Balance")
print("2. Deposit Money")
print("3. Withdraw Money")

# Taking user's choice
choice = int(input("Enter your choice (1/2/3): "))

# Handling choices
if choice == 1:
    print(f"Your current balance is ₹{balance}")
elif choice == 2:
    amount = float(input("Enter amount to deposit: "))
    if amount > 0:
        balance += amount
        print(f"Deposit successful! New balance is ₹{balance}")
    else:
        print("Invalid amount entered.")
elif choice == 3:
    amount = float(input("Enter amount to withdraw: "))
    if 0 < amount <= balance:
        balance -= amount
        print(f"Withdrawal successful! New balance is ₹{balance}")
    else:
        print("Insufficient balance or invalid amount.")
else:
    print("Invalid choice. Please try again.")

# Q14 Write a program that categorizes a given age into different groups:
# Infant (0-1 year)
# Toddler (2-4 years)
# Child (5-12 years)
# Teenager (13-19 years)
# Adult (20-59 years)
# Senior (60 years and above)


# Taking input for age
age = int(input("Enter the age: "))

# Categorizing based on age
if 0 <= age <= 1:
    print("Category: Infant")
elif 2 <= age <= 4:
    print("Category: Toddler")
elif 5 <= age <= 12:
    print("Category: Child")
elif 13 <= age <= 19:
    print("Category: Teenager")
elif 20 <= age <= 59:
    print("Category: Adult")
elif age >= 60:
    print("Category: Senior")
else:
    print("Invalid age entered.")

# Q15 Write a program that takes an integer (1-7) as input and prints the corresponding day of the week (1
# for Monday, 2 for Tuesday, etc.).


# Taking input
day_number = int(input("Enter a number (1-7): "))

# Matching the day
if day_number == 1:
    print("Monday")
elif day_number == 2:
    print("Tuesday")
elif day_number == 3:
    print("Wednesday")
elif day_number == 4:
    print("Thursday")
elif day_number == 5:
    print("Friday")
elif day_number == 6:
    print("Saturday")
elif day_number == 7:
    print("Sunday")
else:
    print("Invalid input! Please enter a number between 1 and 7.")

# ///////////complete assignment

`# Loops
for i in range(5,1,-1):
  print("hey",i)

total=0

for i in range(1,8):

  total=total+i  #total=3+3
  print("hey",i,total)

total=0

for i in range(95,57, -1):

  total=total+i  #total=3+3
  print("hey",total)

total=0

for i in range(1,7):
  if(i%2==0):
    print("divided by 2 =>",i)

# 40 se 18 tak muje sare oddd numbers ka sum nikal kar dikhao


total = 0

for i in range(40, 17, -1):
    if i % 2 != 0:
        total += i

print("odd numbers", total)

print(ord("C"))

print(chr(65))

x="yash"
for i in x:    #x=> iterable (for loop)
  print(i)

data="yash"
data[3]
for i in range(0,4):
  print(i,data[i])      #dat[3]

data="Heyuser"
for i in range(0,len(data)):

  print(i,data[i])

# Assignment- For loop 26/04/2025


# 1. Write a program to print all natural numbers from 1 to n. – using while
# loop


n = int(input("Enter the value of n: "))

i = 1

while i <= n:
    print(i, end=" ")
    i += 1

# 2. Write a program to print all natural numbers in reverse (from n to 1). –
# using while loop


n = int(input("Enter the value of n: "))


i = n

while i >= 1:
    print(i, end=" ")
    i -= 1

# 3. Write a program to print all alphabets from a to z. – using while loop

char = 'a'


while char <= 'z':
    print(char, end=" ")
    char = chr(ord(char) + 1)

# 4. Write a program to print all even numbers between 1 to 100. – using
# while loop


num = 2
1
while num <= 100:
    print(num, end=" ")
    num += 2

# 5. Write a program to find the sum of all odd numbers between 1 to n.


n = int(input("Enter the value of n: "))


sum_odd = 0


for num in range(1, n+1):
    if num % 2 != 0:
        sum_odd += num


print(f"The sum of all odd numbers between 1 and {n} is: {sum_odd}")

# 6. Write a program to count the number of digits in a number.

num = int(input("Enter a number: "))


count = 0


while num != 0:
    num //= 10
    count += 1


print(f"The number of digits is: {count}")

# 7. Write a program to calculate the sum of digits of a number.


num = int(input("Enter a number: "))


sum_digits = 0


while num != 0:
    sum_digits += num % 10
    num //= 10


print(f"The sum of digits is: {sum_digits}")

# 8. Write a program to find the first and last digit of a number.

num = int(input("Enter a number: "))


last_digit = num % 10


first_digit = num
while first_digit >= 10:
    first_digit //= 10


print(f"The first digit is: {first_digit}")
print(f"The last digit is: {last_digit}")

# 9. Write a program to find the sum of first and last digit of a number.


num = int(input("Enter a number: "))


last_digit = num % 10


first_digit = num
while first_digit >= 10:
    first_digit //= 10


sum_digits = first_digit + last_digit


print(f"The sum of the first and last digit is: {sum_digits}")

# 10.Write a program to enter a number and print its reverse.


num = int(input("Enter a number: "))


reverse = 0


while num != 0:
    reverse = reverse * 10 + num % 10
    num //= 10


print(f"The reverse of the number is: {reverse}")

# 11.Write a program to find the power of a number using for loop.

# 12.Write a program to find all factors of a number.

num = int(input("Enter a number: "))

print(f"Factors of {num} are:")

for i in range(1, num + 1):
    if num % i == 0:
        print(i)

# 13.Write a program to calculate the factorial of a number.

num = int(input("Enter a number: "))

factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, num + 1):
        factorial *= i
    print(f"The factorial of {num} is {factorial}")

# 14.Write a program to find LCM of two numbers.

def find_lcm(x, y):
    if x > y:
        greater = x
    else:
        greater = y
    while(True):
        if((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("The LCM of", num1,"and", num2,"is", find_lcm(num1, num2))

# 15.Write a program to check whether a number is Prime number or not.


num = int(input("Enter a number: "))


if num <= 1:
    print(f"{num} is not a prime number.")
else:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")

1i=1
while(i<5):
  print("hey",i)
  i+=1

# 3 to 76 => get the total of all numbers
# i=1
# while(i<5):
#   print("hey",i)
#   i+=1


i = 3
total = 0

while i <= 76:
    total += i
    i += 1

print("The total sum from 3 to 76 is:", total)

num=2379
while(num>0):
  rem=num%10
  num=num//10
  print("Values are", rem, num)

# ek loop chalo 80 to 20 and print all those numbers which are divided by 7


i = 80
while (i >= 20):
    if (i % 7 == 0):
        print(i)
    i -= 1

#  ek loop chlana h 1 to 150 tak
# then count the total of all the numbers which are odd
# and also count the total odd values

sum_of_odds = 0
count_of_odds = 0


for i in range(1, 151):
    if i % 2 != 0:
        sum_of_odds += i
        count_of_odds += 1

print("Total sum of odd numbers from 1 to 150 is:", sum_of_odds)
print("Total count of odd numbers from 1 to 150 is:", count_of_odds)

# take an number using while loop print all the factors

num = int(input("Enter a number: "))

i = 1

while i <= num:
    if num % i == 0:
        print(i)
    i += 1

# break

for i in range(1,6):
  print(i)
  break
  print("jjjjnjnjjjjccj")


  print("--outside loop---")

# continue


for i in range(1, 6):
    if i == 3:
        continue
    print(i)

print("--outside loop--")

# print 1 to 100 whose value is not count who will divided by 2 & 3


total = 0

for i in range(1, 101):
    if i % 2 != 0 and i % 3 != 0:
        print(i, end=' ')
        total += i

print("\nSum of these numbers is:", total)

# Take a number and print & count all its factors using while loop

num = 8

i = 1
count = 0

while i <= num:
    if num % i == 0:
        print(i)
        count += 1
    i += 1

print("Total number of factors:", count)

# num =8
# check prime numbers

# num=5
# count=0
# for i in range(1,num+1):
#   if(num%i==0):
#     x=1
#     break
#     i+1

#     # outside loop
#     if(x==1):
#       print("Not prime")
#     else:
#         print("prime")

num = 5
count = 0
x = 0

for i in range(1, num + 1):
    if(num % i == 0):
        count += 1

if count == 2:
    print("Prime")
else:
    print("Not prime")

i = 2
a = 0
while(i < 9):
    if(i == 100):
        a = 1
        break
    i += 1

    if(a == 0):
        print("loop purra")
    else:
        print("loop break hua")

#nested loop
#nested loop => loop with in a loop

for i in range(1,6):
  print("--student",i)

  for j in range(1,4):
    print

for i in range(1, 6):
    print("--student", i)

    for j in range(1, i + 1):
        print("subject", j)

# nested loop other condition

for i in range(1, 5):
    print("--student", i)

    for j in range(i,5):
        print("subject", j)

for i in range(1, 5):
    print("--student", i)

    for j in range(1,6-i): #(1,6-2)
        print("subject", j)

for i in range(4,0,-1):
    print("--student", i)

    for j in range(i,5):
        print("subject", j)

# table print
num=2
for i in range(1,11):
  print(num*i)

for num in range(2, 6):
    for i in range(1, 11):
        print(num * i)

for num in range(2, 10):
    for i in range(1, num+1):
      if(num%i==0):
        print("factor =>",i)

        print("---")

